# Generated by Django 2.2 on 2020-09-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itequp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itequp.CompanyMaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itequp.DepartmentMaster')),
            ],
        ),
        migrations.CreateModel(
            name='AllocateDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('purchase_date', models.DateField()),
                ('serial_number', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itequp.DeviceType')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itequp.Employee')),
            ],
        ),
    ]
