# Generated by Django 2.2 on 2020-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itequp', '0002_allocatedevice_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedevice',
            name='assign_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
