# Generated by Django 2.2 on 2020-09-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itequp', '0004_auto_20200916_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedevice',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itequp.Supplier'),
        ),
    ]
