# Generated by Django 2.2 on 2020-09-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itequp', '0005_allocatedevice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedevice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itequp.Supplier'),
        ),
    ]
